<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>config</string>
		<string>cfg</string>
	</array>
	<key>name</key>
	<string>Ericsson IPOS</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>context_string.text.ipos</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>context_name.text.ipos</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>context_vpn_id.text.ipos</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Main context name</string>
			<key>match</key>
			<string>^(context)\s(\w+)\svpn-rd\s(\d+\:\d+)</string>
			<key>name</key>
			<string>context.text.ipos</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>context_string.text.ipos</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>context_name.text.ipos</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Main context name</string>
			<key>match</key>
			<string>^(context)\s(\w+)</string>
			<key>name</key>
			<string>text.ipos</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Routing protocols</string>
			<key>match</key>
			<string>^.router\s(bfd|ospf|bgp|ospv3|mpls|ldp|rip|nd)</string>
			<key>name</key>
			<string>router.text.ipos</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>ipaddr.text.ipos</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>ipaddrmask.text.ipos</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>IP address without slash</string>
			<key>match</key>
			<string>\s(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})\/(\d{1,2})</string>
			<key>name</key>
			<string>ipaddr.text.ipos</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>IP address without slash</string>
			<key>match</key>
			<string>(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})</string>
			<key>name</key>
			<string>ipaddr.text.ipos</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>service_word</string>
			<key>match</key>
			<string>area\s|set\s|match\s</string>
			<key>name</key>
			<string>service_words.text.ipos</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>interface.text.ipos</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>interface_name.text.ipos</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>interface_type.text.ipos</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s+(interface)\s(\w+)\s(\w+)</string>
			<key>name</key>
			<string>text.ipos</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>interface.text.ipos</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>interface_name.text.ipos</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s+(interface)\s(\w+)</string>
			<key>name</key>
			<string>text.ipos</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>ip_address.text.ipos</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>ipaddrmask.text.ipos</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>IP address string</string>
			<key>match</key>
			<string>^\s+(ip\saddress)\s(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})\/(\d{1,2})</string>
			<key>name</key>
			<string>text.ipos</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>router_id</string>
			<key>match</key>
			<string>router-id\s|neighbor|peer-group|service|enable|remote-as|admin-access-group|redistribute|role|privilege|encrypted-key</string>
			<key>name</key>
			<string>router_id.text.ipos</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>service</string>
			<key>match</key>
			<string>\svrrp\s|virtual-address|update-source|full-name|snmp|encapsulation</string>
			<key>name</key>
			<string>vrrp_soon.text.ipos</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>administrator.text.ipos</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>user_name.text.ipos</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>user records</string>
			<key>match</key>
			<string>^\s+(administrator)\s(\w+)\s</string>
			<key>name</key>
			<string>admin.text.ipos</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>radius.text.ipos</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>radius_word.text.ipos</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>RADIUS</string>
			<key>match</key>
			<string>^\s(radius)\s(\w+)\s</string>
			<key>name</key>
			<string>text.ipos</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>aaa.text.ipos</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>aaa_word.text.ipos</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>RADIUS</string>
			<key>match</key>
			<string>^\s(aaa)\s(\w+)\s</string>
			<key>name</key>
			<string>text.ipos</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s+(no)\s</string>
			<key>name</key>
			<string>no.text.ipos</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>class.text.ipos</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>class_name.text.ipos</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>class and class name</string>
			<key>match</key>
			<string>(class)\s(.+)</string>
			<key>name</key>
			<string>class.text.ipos</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>acl_permit.text.ipos</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>acl_deny.text.ipos</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>ACL permit and deny</string>
			<key>match</key>
			<string>\s(permit)\s|\s(deny)\s</string>
			<key>name</key>
			<string>text.ipos</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>comminity string</string>
			<key>match</key>
			<string>\s\d+\:\d+\s</string>
			<key>name</key>
			<string>community.text.ipos</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>description_string.text.ipos</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>description_body.text.ipos</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>description string</string>
			<key>match</key>
			<string>(description\s)(.+)</string>
			<key>name</key>
			<string>description.text.ipos</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>ip_access_list.text.ipos</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>ip_prefix_list.text.ipos</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>name_acl_prf.text.ipos</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(ip\saccess-list)|(ip\sprefix-list)\s(\w+)</string>
			<key>name</key>
			<string>access_prefix_list.text.ipos</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>route_map.text.ipos</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>route_map_name.text.ipos</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>route_map_permit.text.ipos</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>route_map.text.ipos</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>route_map_name.text.ipos</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>route_map_deny.text.ipos</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s+(route-map)\s(.+)\s(permit)\s|^\s+(route-map)\s(.+)\s(deny)\s</string>
			<key>name</key>
			<string>route_map.text.ipos</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>route_map.text.ipos</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>route_map_name.text.ipos</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>route_map_permit.text.ipos</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>route_map.text.ipos</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>route_map_name.text.ipos</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>route_map_deny.text.ipos</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s+(route-map)\s(.+)\s(in)\s|^\s+(route-map)\s(.+)\s(out)\s</string>
			<key>name</key>
			<string>text.ipos</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>default.text.ipos</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>default_gw.text.ipos</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s+(ip\sroute\s0\.0\.0\.0\/0)\s(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})</string>
			<key>name</key>
			<string>text.ipos</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>hostname.text.ipos</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>hostname</string>
			<key>match</key>
			<string>\](\w+)\#</string>
			<key>name</key>
			<string>text.ipos</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>qos plicy</string>
			<key>match</key>
			<string>^qos\spolicy\s</string>
			<key>name</key>
			<string>aaa.text.ipos</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>qos_type.text.ipos</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>card_family.text.ipos</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>card_num.text.ipos</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\s(metering)\s(card-family)\s(\d)</string>
			<key>name</key>
			<string>text.ipos</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>qos_type.text.ipos</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>card_family.text.ipos</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>card_num.text.ipos</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\s(policing)\s(card-family)\s(\d)</string>
			<key>name</key>
			<string>text.ipos</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>aaa.text.ipos</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>interface_name.text.ipos</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>context_name.text.ipos</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\s(bind\sinterface)\s(\w+)\s(\w+)</string>
			<key>name</key>
			<string>text.ipos</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>aaa.text.ipos</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>no.text.ipos</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\s(dot1q\spvc)\s(\d+)</string>
			<key>name</key>
			<string>text.ipos</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>aaa.text.ipos</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>no.text.ipos</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(port\sethernet)\s(\d+\/\d+)</string>
			<key>name</key>
			<string>text.ipos</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.ipos</string>
	<key>uuid</key>
	<string>27724496-8243-484d-bb2b-9cb177cb73c8</string>
</dict>
</plist>
